port: 3500
mongo:
  url: ""
  dbName: ""
  collectionName: ""
jwt:
  secret: ""
  expiresIn: ""
email:
  service: ""
  host: ""
  port: ""
  auth:
    user: ""
    pass: ""
  from:
    name: ""
    address: ""
  subject: ""
google:
  clientId: ""