port: 3500
mongo:
  url: mongodb://localhost:27017
  dbName: tracker-expense-db
  collectionName: expenses
jwt:
  secret: secret_jwt_key145@#$
  expiresIn: 4h
email:
  service: gmail
  host: smtp.gmail.com
  port: 587
  auth:
    user: adrianbravo145@gmail.com
    pass: twra xwcm jzgd vwwk
  from:
    name: Expense-tracker@test.com
    address: Expense-tracker@test.com
  subject: Expense Tracker